### ISSUE TITLE
Resource Lode generation on Kerbin allows for Infinite Money in Career mode

### ISSUE THREAD

**Issue by SergeySave** [BobPalmer/ExplorationPack#111]
**Replication Steps:**
1. Put a satellite with a [M700 Survey Scanner](http://wiki.kerbalspaceprogram.com/wiki/M700_Survey_Scanner) into a polar orbit around kerbin between 300k and 600k altitude.
2. Deploy the scanner
3. Press scan for resource lodes
4. Go to map view
5. Click on the resource lode (appears as a question mark)
6. Press switch to
7. Recover the resource lode

**Recovery Screen:**
![Recovery Screen](http://i.imgur.com/ge9OEye.jpg)

**Modlist:**
USITools
xScience
CommunityResourcePack
CommunityCategoryKit
DockingPortAlignmentIndicator
Konstruction
PersistentRotation
LaunchNumbering
InterstellarFuelSwitch-Core
InterstellarFuelSwitch
PreciseNode
Toolbar
KIS
TweakScale
KerbalAlarmClock
PilotAssistant
EasyVesselSwitch
Trajectories
ConfigurableContainers-Core
USI-Core
UKS
CommunityTechTree
ModuleManager
TransferWindowPlanner
WaypointManager
ThrottleControlledAvionics
FirespitterCore
KAS
AT-Utils
StageRecovery
USI-LS
KSPInterstellarExtended
KerbalJointReinforcement
KerbalEngineerRedux
CapCom
ProgressParser
ContractParser

**Comment by BobPalmer** [comment]
Fixed next release
