### ISSUE TITLE
Part suggestion: LF Generator that could power 2-4 Ducted fan engines 

### ISSUE THREAD

**Issue by Grunf911** [BobPalmer/ExplorationPack#25]
Ducted fan engines look and feel wise could be used with other mods i.e. B9 to create VTOL SSTOs.

The problem is that currently Ducted Fan engine requires ElectricCharge only provided by nuclear generators. Making LF powered Generator(s) that could power 2-4 ducted fan engines would expand the use of ducted fan engine way beyond the just mod scope. Proposal would be the following:

1x Small LF generator - able to power 2x Ducted fans
2x Medium LF generator - able to power 4x Ducted fans

They should be fuel efficient enough, but not too fuel efficient so they are not mis-used for Electric charge generation on longer trips

**Comment by BobPalmer** [comment]
Closing since we now have stock fuel cells
