### ISSUE TITLE
Safety Light KAS size

### ISSUE THREAD

**Issue by Huntarr** [BobPalmer/ExplorationPack#36]
In reference to the thread post about the Safety Light being so KAS large

My suggestion was to make it 8, in line with Squad Lights.  Currently it is 20

http://forum.kerbalspaceprogram.com/threads/86695-0-25-USI-Exploration-Pack-Small-parts-big-adventure%21-v-0-2-5-2014-11-01?p=1520022&viewfull=1#post1520022

BTW this was my first Github, hope I got it where you wanted it.

**Comment by BobPalmer** [comment]
Closing this as KAS has been deprecated in favor of KIS
