### ISSUE TITLE
Reusability issue with the PackRat Rover MiniWheel

### ISSUE THREAD

**Issue by andschenk** [BobPalmer/ExplorationPack#38]
The MiniWheel can only be taken out of a KAS container once. If it is stored again and taken out of the the container again, it won't properly attach to the Kerbal and subequent KAS actions are broken.

Steps to reproduce:
1) Create vessel with KAS container containing MiniWheel in VAB
2) During flight EVA take MiniWheel out of container.
3) Attach MiniWheel to vessel.
4) Grab MiniWheel and store it in container.
5) Take MiniWheel out of container again (log shows NullReferenceException).

---------------------- log file -----------------------------------------
[LOG 21:58:30.144] [KAS] WaitAndGrab(Container) - Waiting rigidbody to initialize...
[ERR 21:58:30.147] WheelCollider requires an attached Rigidbody to function.

[LOG 21:58:30.210] [KAS] WaitAndGrab(Container) - Waiting rigidbody to initialize...
[LOG 21:58:30.216] [KAS] WaitAndGrab(Container) - Waiting rigidbody to initialize...
[LOG 21:58:30.237] [KAS] WaitAndGrab(Container) - Rigidbody initialized, setting velocity...
[LOG 21:58:30.238] [KAS] WaitAndGrab(Container) - Waiting velocity to apply by waiting 0.1 seconds...
[LOG 21:58:30.342] [KAS] WaitAndGrab(Container) - Grab part...
[LOG 21:58:30.382] [KAS] Grab - Grabbing part :PackRat.MiniWheel
[LOG 21:58:30.422] [KAS] WaitAndGrab(Container) - End of coroutine...
[WRN 21:58:30.439] [PartJoint]: None of the provided nodes was valid!
[LOG 21:58:30.441] RemoteTech: SatelliteManager: OnVesselDestroy(afa5d398-5cbb-4426-9259-86c43d7c6547, PackRat Mini Wheel)
[LOG 21:58:30.442] RemoteTech: SatelliteManager: UnregisterProto(afa5d398-5cbb-4426-9259-86c43d7c6547)
[LOG 21:58:30.447] [IR GUI] vessel kerbalEVA (Dudmund Kerman)
[LOG 21:58:30.448] [IR GUI] 0 groups
[LOG 21:58:38.049] SCREENSHOT!!
[LOG 21:58:46.368] [KAS] StartPointer(pointer)
[ERR 21:58:46.386] WheelCollider requires an attached Rigidbody to function.

[LOG 21:58:47.257] [KAS] Attachment started...
[LOG 21:58:47.258] [KAS] Drop - Dropping part :PackRat.MiniWheel
[LOG 21:58:47.260] RemoteTech: SatelliteManager: OnVesselCreate(bc7c3616-db92-4f9b-95e0-56686ae27d51, )
[LOG 21:58:47.267] [IR GUI] vessel kerbalEVA (Dudmund Kerman)
[LOG 21:58:47.268] [IR GUI] 0 groups
[LOG 21:58:47.347] [KAS] UpdatePointer(Pointer) Attach with couple or static method
[LOG 21:58:47.348] RemoteTech: SatelliteManager: OnVesselDestroy(bc7c3616-db92-4f9b-95e0-56686ae27d51, Dudmund Kerman Debris)
[LOG 21:58:47.349] RemoteTech: SatelliteManager: UnregisterProto(bc7c3616-db92-4f9b-95e0-56686ae27d51)
[LOG 21:58:51.292] [KAS] Grab - Grabbing part :PackRat.MiniWheel
[LOG 21:58:51.332] RemoteTech: SatelliteManager: OnVesselCreate(c5facd2d-5560-4938-b39c-91206a863c4e, )
[ERR 21:58:51.334] Input is null

[WRN 21:58:51.353] [PartJoint]: None of the provided nodes was valid!
[LOG 21:58:51.354] RemoteTech: SatelliteManager: OnVesselDestroy(c5facd2d-5560-4938-b39c-91206a863c4e, Untitled Space Craft Debris)
[LOG 21:58:51.355] RemoteTech: SatelliteManager: UnregisterProto(c5facd2d-5560-4938-b39c-91206a863c4e)
[LOG 21:58:51.361] [IR GUI] vessel kerbalEVA (Dudmund Kerman)
[LOG 21:58:51.362] [IR GUI] 0 groups
[LOG 21:58:54.922] [KAS] Drop - Dropping part :PackRat.MiniWheel
[LOG 21:58:54.924] RemoteTech: SatelliteManager: OnVesselCreate(b4c4dc66-9071-4b93-a2f3-ad6933e082dc, )
[LOG 21:58:54.931] [IR GUI] vessel kerbalEVA (Dudmund Kerman)
[LOG 21:58:54.931] [IR GUI] 0 groups
[LOG 21:58:55.010] [PackRat.MiniWheel]: Deactivated
[LOG 21:58:55.015] RemoteTech: SatelliteManager: OnVesselDestroy(b4c4dc66-9071-4b93-a2f3-ad6933e082dc, Dudmund Kerman Debris)
[LOG 21:58:55.016] RemoteTech: SatelliteManager: UnregisterProto(b4c4dc66-9071-4b93-a2f3-ad6933e082dc)
[LOG 21:59:00.436] [KAS] GrabPending - Preparing To Grab part :PackRat.MiniWheel
[EXC 21:59:00.552] NullReferenceException
	UnityEngine.Component.get_gameObject ()
	KAS.KAS_Shared.FinishDelayedCreation (.Part part, System.Collections.Generic.List`1 re_enable)
	KAS.KAS_Shared+<WaitAndUnpack>d__0.MoveNext ()

**Comment by BobPalmer** [comment]
Closing as KIS has replaced KAS
