### ISSUE TITLE
HERP_MaintPod Missing node_attach

### ISSUE THREAD

**Issue by Tebryn** [BobPalmer/ExplorationPack#44]
Surface Attachment is enabled, but no node_attach is defined so the defaults to the center of the part. 

not a big issue with part rotation and offsetting in .90 but it's an easy fix

``` node_attach = 0, -0.65, 0, 0.0, -1.0, 0.0, 0 ```

same node location as node_stack_Bottom with the connection axis inverted.

https://github.com/BobPalmer/ExplorationPack/blob/master/GameData/UmbraSpaceIndustries/ExpPack/MaintPod/MaintPod.cfg

currently have this fixed on my install with a simple MM patch, works fine.

**Comment by BobPalmer** [comment]
This part has been deprecated
