### ISSUE TITLE
[Feature request] Add MechJeb functionality to the small pods.

### ISSUE THREAD

**Issue by smjjames** [BobPalmer/ExplorationPack#50]
The AR202 case is almost the size of the side of the AEV pod. I'm looking into how to add them myself, but adding MechJeb functionality to them might be cool.

**Comment by BobPalmer** [comment]
Should just be a MM patch and I think there's another mod that does this already

**Comment by BobPalmer** [comment]
Closing as this is a bit orthagonal to this mod.
