### ISSUE TITLE
heatDissipation in UmbraSpaceIndustries/ExpPack/AES/AES_Beam/AES_Beam

### ISSUE THREAD

**Issue by RealKolago** [BobPalmer/ExplorationPack#52]
Variable "heatDissipation" does not exist in KSP:

PartLoader: Compiling Part 'UmbraSpaceIndustries/ExpPack/AES/AES_Beam/AES_Beam'
(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)
PartLoader Warning: Variable heatDissipation not found in Part

**Comment by BobPalmer** [comment]
Fixed
