### ISSUE TITLE
EVA spinning

### ISSUE THREAD

**Issue by webanck** [BobPalmer/ExplorationPack#55]
> Hello there, I don't know if anyone has signaled it yet but the ModuleRCSFX included in the Exploration Pack mod is causing serious troubles when trying to EVA in space.
> I was not able to control anything and had to diagnostic it with a new stock save to isolate, adding mods mods in a dichotomous way.
> So yeah, without this directory in my GameData, all is fine!

**Comment by BobPalmer** [comment]
Closing - unable to repro
