### ISSUE TITLE
HERP Jumpseat node upsidedown

### ISSUE THREAD

**Issue by Peppe-KSP** [BobPalmer/ExplorationPack#61]
ExpPack/HERP/parts/HERP_JumpSeat.cfg
node_stack_bottom = 0, -0.22, 0, 0.0, 1.0, 0.0, 0

Switching to this resolves the issue for me:
node_stack_bottom = 0, -0.22, 0, 0.0, -1.0, 0.0, 0

**Comment by smjjames** [comment]
Confirmed still.
