### ISSUE TITLE
AES Cargo Rack One Horizontal Node is backward

### ISSUE THREAD

**Issue by Peppe-KSP** [BobPalmer/ExplorationPack#62]
ExpPack/AES/AES_Rack.cfg
node_stack_Cargo_2 = -0.03, 0, 0, 1.0, 0, 0.0, 0

Resolved with:
node_stack_Cargo_2 = -0.03, 0, 0, -1.0, 0, 0.0, 0

**Comment by BobPalmer** [comment]
Fixed
