### ISSUE TITLE
PackRat Parts KIS Values too large

### ISSUE THREAD

**Issue by NyankoSensei** [BobPalmer/ExplorationPack#76]
Now for Transport packrat is need a 2,5m kontainer, probably is better revert https://github.com/BobPalmer/ExplorationPack/issues/65 to some sane values, on this way can fit inside 1.25 kontainer

PackratKis_Fix.cfg
@PART[PackRat_MiniWheel] {
!MODULE[ModuleKISItem] {}
	MODULE
	{
		name = ModuleKISItem
		volumeOverride = 100
		carriable = false
		editorItemsCategory = false
	}
}

@PART[PackRat_Back] {
!MODULE[ModuleKISItem] {}
	MODULE
	{
		name = ModuleKISItem
		volumeOverride = 500
		equipSlot = Back Pocket
		carriable = true
		editorItemsCategory = false
	}
}

@PART[PackRat_Camera] {
!MODULE[ModuleKISItem] {}
	MODULE
	{
		name = ModuleKISItem
		volumeOverride = 50
		carriable = false
		editorItemsCategory = false
	}
}

@PART[PackRat_Chassis_Front] {
!MODULE[ModuleKISItem] {}
	MODULE
	{
		name = ModuleKISItem
		volumeOverride = 250
		carriable = false
		editorItemsCategory = false
	}
}

@PART[PackRat_Chassis_Rear] {
!MODULE[ModuleKISItem] {}
	MODULE
	{
		name = ModuleKISItem
		volumeOverride = 250
		carriable = false
		editorItemsCategory = false
	}
}

@PART[PackRat_Crate] {
!MODULE[ModuleKISItem] {}
	MODULE
	{
		name = ModuleKISItem
		volumeOverride = 50
		carriable = false
		editorItemsCategory = false
	}
}

@PART[PackRat_Front] {
!MODULE[ModuleKISItem] {}
	MODULE
	{
		name = ModuleKISItem
		volumeOverride = 500
		equipSlot = Back Pocket
		carriable = true
		editorItemsCategory = false
	}
}

@PART[PackRat_RoofRack] {
!MODULE[ModuleKISItem] {}
	MODULE
	{
		name = ModuleKISItem
		volumeOverride = 150
		carriable = false
		editorItemsCategory = false
	}
}

@PART[PackRat_Seat] {
	MODULE
	{
		name = ModuleKISItem
		volumeOverride = 50
		carriable = false
		editorItemsCategory = false
	}
}

**Comment by BobPalmer** [comment]
These would be much better as a pull request :)

**Comment by BobPalmer** [comment]
In next release
