### ISSUE TITLE
AES Pod Internals not staying connected to frame

### ISSUE THREAD

**Issue by tito13kfm** [BobPalmer/ExplorationPack#83]
The AES Pod internals immediately fall through the ground upon loading to launchpad.  Switching to IVA view only shows instrument panel, all other internals are missing.

Album showing issue:

http://imgur.com/a/chu9y

Log attached
[output_log.txt](https://github.com/BobPalmer/ExplorationPack/files/205246/output_log.txt)

**Comment by smjjames** [comment]
Confirmed for 1.1 full. I'm also seeing an error thrown during the load-up proccess when starting.

**Comment by BobPalmer** [comment]
Fixed in next release
